/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#bec6e0",
        "on-tertiary-container": "#d6e6ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#001452",
        "surface-tint": "#004ced",
        "on-secondary-fixed-variant": "#3f465c",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "surface-container-low": "#f2f4f6",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#0b1c30",
        "secondary-fixed": "#dae2fd",
        "primary-fixed-dim": "#b7c4ff",
        "on-surface": "#191c1e",
        "surface-container": "#eceef0",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#131b2e",
        "secondary-container": "#dae2fd",
        "primary": "#0052FF",
        "tertiary": "#3f4f65",
        "secondary": "#565e74",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#dfe3ff",
        "on-surface-variant": "#434656",
        "on-background": "#191c1e",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "on-secondary-container": "#5c647a",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed": "#dde1ff",
        "primary-container": "#0052ff",
        "surface-dim": "#d8dadc",
        "surface-container-high": "#e6e8ea",
        "surface-bright": "#f7f9fb",
        "surface": "#f7f9fb",
        "on-primary-fixed-variant": "#0038b6",
        "outline": "#737688",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e3e5",
        "tertiary-container": "#57677e",
        "inverse-primary": "#b7c4ff",
        "outline-variant": "#c3c5d9",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-tertiary-fixed-variant": "#38485d",
        "tertiary-fixed": "#d3e4fe"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
